require_relative './matrix_gem/matrix_err'
require_relative './matrix_gem/properties_module'
require_relative './matrix_gem/matrix'
require_relative './matrix_gem/diagonal_matrix'
require_relative './matrix_gem/orthogonal_matrix'